package org.iranshahi.zoochallenge.data.model;

import lombok.*;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;


/**
 * Represents a physical or logical room within the zoo facility.
 * <p>
 * Each {@code Room} is used to house zero or more {@link org.iranshahi.zoochallenge.data.model.Animal Animal}s.
 * Rooms are created and managed via the {@code RoomService} and can be used as both
 * current locations and "favourite" destinations for animals.
 * </p>
 *
 * <h3>Persistence</h3>
 * <ul>
 *   <li>Stored in collection: <b>rooms</b></li>
 *   <li>Each document has an autogenerated {@code id}</li>
 *   <li>Auditing fields ({@code created}, {@code updated}) are automatically populated by Spring Data</li>
 * </ul>
 *
 * <h3>Indexes</h3>
 * The {@code title} field is indexed for fast lookup and sorting.
 *
 * <h3>Usage</h3>
 * This entity is referenced by:
 * <ul>
 *   <li>{@link org.iranshahi.zoochallenge.data.model.Animal#getRoomId()}</li>
 *   <li>{@link org.iranshahi.zoochallenge.data.model.Animal#getFavouriteRoomIds()}</li>
 * </ul>
 *
 * @author Reza Iranshahi
 * @see org.iranshahi.zoochallenge.data.repository.RoomRepository
 * @since 9 Oct 2025
 */
@Document(collection = "rooms")
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Getter
@Setter
public class Room {
    @Id
    private String id;

    @Indexed
    private String title;

    @CreatedDate
    private Instant created;

    @LastModifiedDate
    private Instant updated;
}
